Add contrib action for OHI release (NR-83896) (#135)
* Add contrib action for OHI release
* fix typos
* add a toggle for the link dependencies step
* change readme script run from main to v1
* Do not require a dictionary to link dependencies
* add tests and git-root parameter
* missing yaml in at link step
* typo while rendering markdown snippet
* typo while running script
* Fix renderer as it is not adding a line jump in the end
* use action versions that are already downloaded
* rename the action to ohi-release-notes
* add missing tests and make them more verbose
* typos

diff --git a/.github/workflows/self_test.yaml b/.github/workflows/self_test.yaml
--- a/.github/workflows/self_test.yaml
+++ b/.github/workflows/self_test.yaml
@@ -427,3 +427,220 @@ jobs:
             echo "valid should have returned false" >&2
             exit 1
           fi
+
+  contrib-ohi-release-notes:
+    name: validate ohi-release-notes (contrib action)
+    runs-on: ubuntu-latest
+    env:
+      MOCK_REPO_ACTION: ./mock_repo_action
+      MOCK_REPO_SCRIPT: ./mock_repo_script
+      ACTION_OUTPUTS: ./action_outputs
+    steps:
+      - uses: actions/checkout@v3
+      - name: Configure test repo
+        shell: bash
+        run: |
+          # MOCK_REPO_SCRIPT is not needed as it is copied from ACTION one.
+          mkdir -pv "${MOCK_REPO_ACTION}" "${ACTION_OUTPUTS}"
+          cd "${MOCK_REPO_ACTION}"
+
+          git config --global user.email "you@example.com"
+          git config --global user.name "Your Name"
+
+          git init
+          cat > CHANGELOG.md <<EOF
+          # Changelog
+            This is based on blah blah blah
+
+          ## v1.2.3 - 20YY-DD-MM
+
+          ### Enhancements
+          - This is in the past and should be preserved
+          EOF
+
+          git add CHANGELOG.md
+          for i in 1 2 3; do
+            touch file$i
+            git add file$i
+            git commit -m commit_$i
+          done
+          git tag 1.2.3
+
+
+          cat > CHANGELOG.md <<EOF
+          # Changelog
+            This is based on blah blah blah
+
+          ## Unreleased
+          ### Enhancement
+          - test
+
+          ## v1.2.3 - 20YY-DD-MM
+
+          ### Enhancements
+          - This is in the past and should be preserved
+          EOF
+
+          cd $OLDPWD
+          cp -r "${MOCK_REPO_ACTION}" "${MOCK_REPO_SCRIPT}"
+      - name: Expected CHANGELOG
+        shell: bash
+        run: |
+          cat > expected-changelog.md <<EOF
+          # Changelog
+            This is based on blah blah blah
+
+          ## Unreleased
+
+          ## v1.3.0 - $(date +%Y-%m-%d)
+
+          ### 🚀 Enhancements
+          - test
+
+          ## v1.2.3 - 20YY-DD-MM
+
+          ### Enhancements
+          - This is in the past and should be preserved
+          EOF
+      - name: Expected partial CHANGELOG
+        shell: bash
+        run: |
+          cat > expected-partial.md <<EOF
+          ## v1.3.0 - $(date +%Y-%m-%d)
+
+          ### 🚀 Enhancements
+          - test
+          EOF
+
+      - name: Run action
+        uses: ./contrib/ohi-release-notes
+        id: ohi-release-notes
+        with:
+          git-root: ${{ env.MOCK_REPO_ACTION }}
+      - name: Run script
+        run: |
+          cd "${{ env.MOCK_REPO_SCRIPT }}"
+          # CLI autodetects whether it is running on GHA or not. If we let GHA set this to true, as it normally does,
+          # tests cases where GITHUB_ACTIONS is expected to be unset would fail.
+          GITHUB_ACTIONS=false "${GITHUB_WORKSPACE}/contrib/ohi-release-notes/run.sh"
+      - name: Action outputs
+        working-directory: ${{ env.ACTION_OUTPUTS }}
+        run: |
+          echo -ne "${{ steps.ohi-release-notes.outputs.changelog }}" > CHANGELOG.md
+          echo -ne "${{ steps.ohi-release-notes.outputs.changelog-partial }}" > CHANGELOG.partial.md
+
+      - name: Asserts
+        run: |
+          exit_status=0
+
+          echo "Action's CHANGELOG.md should be equal"
+          echo RESULT:
+          cat "${{ env.MOCK_REPO_ACTION }}/CHANGELOG.md"
+          echo EXPECTED:
+          cat expected-changelog.md
+          echo TEST:
+          if cmp --silent expected-changelog.md ${{ env.MOCK_REPO_ACTION }}/CHANGELOG.md; then
+            echo PASS
+          else
+            echo FAIL - diff between expected and the output:
+            diff expected-changelog.md ${{ env.MOCK_REPO_ACTION }}/CHANGELOG.md
+            ((exit_status++))
+          fi
+          echo =================================================================
+          echo "script's CHANGELOG.md should be equal"
+          echo RESULT:
+          cat "${{ env.MOCK_REPO_SCRIPT }}/CHANGELOG.md"
+          echo EXPECTED:
+          cat expected-changelog.md
+          echo TEST:
+          if cmp --silent expected-changelog.md ${{ env.MOCK_REPO_SCRIPT }}/CHANGELOG.md; then
+            echo PASS
+          else
+            echo FAIL - diff between expected and the output:
+            diff expected-changelog.md ${{ env.MOCK_REPO_SCRIPT }}/CHANGELOG.md
+            ((exit_status++))
+          fi
+          echo =================================================================
+          echo "script's CHANGELOG.md should be equal"
+          echo RESULT:
+          cat "${{ env.MOCK_REPO_SCRIPT }}/CHANGELOG.md"
+          echo EXPECTED:
+          cat expected-changelog.md
+          echo TEST:
+          if cmp --silent expected-changelog.md ${{ env.MOCK_REPO_SCRIPT }}/CHANGELOG.md; then
+            echo PASS
+          else
+            echo FAIL - diff between expected and the output:
+            diff expected-changelog.md ${{ env.ACTION_OUTPUTS }}/CHANGELOG.md
+            ((exit_status++))
+          fi
+          echo =================================================================
+          echo "Action's CHANGELOG.partial.md should be equal"
+          echo RESULT:
+          cat "${{ env.MOCK_REPO_ACTION }}/CHANGELOG.partial.md"
+          echo EXPECTED:
+          cat expected-partial.md
+          echo TEST:
+          if cmp --silent expected-partial.md ${{ env.MOCK_REPO_ACTION }}/CHANGELOG.partial.md; then
+            echo PASS
+          else
+            echo FAIL - diff between expected and the output:
+            diff expected-partial.md ${{ env.MOCK_REPO_ACTION }}/CHANGELOG.partial.md
+            ((exit_status++))
+          fi
+          echo =================================================================
+          echo "script's CHANGELOG.partial.md should be equal"
+          echo RESULT:
+          cat "${{ env.MOCK_REPO_SCRIPT }}/CHANGELOG.partial.md"
+          echo EXPECTED:
+          cat expected-partial.md
+          echo TEST:
+          if cmp --silent expected-partial.md ${{ env.MOCK_REPO_SCRIPT }}/CHANGELOG.partial.md; then
+            echo PASS
+          else
+            echo FAIL - diff between expected and the output:
+            diff expected-partial.md ${{ env.MOCK_REPO_SCRIPT }}/CHANGELOG.partial.md
+            ((exit_status++))
+          fi
+          echo =================================================================
+          echo "script's CHANGELOG.partial.md should be equal"
+          echo RESULT:
+          cat "${{ env.MOCK_REPO_SCRIPT }}/CHANGELOG.partial.md"
+          echo EXPECTED:
+          cat expected-partial.md
+          echo TEST:
+          if cmp --silent expected-partial.md ${{ env.MOCK_REPO_SCRIPT }}/CHANGELOG.partial.md; then
+            echo PASS
+          else
+            echo FAIL - diff between expected and the output:
+            diff expected-partial.md ${{ env.ACTION_OUTPUTS }}/CHANGELOG.partial.md
+            ((exit_status++))
+          fi
+          echo =================================================================
+          echo "action output 'next-version' return the expected value"
+          echo EXPECTED:
+          echo "v1.3.0"
+          echo RESULT:
+          echo "${{ steps.ohi-release-notes.outputs.next-version }}"
+          echo TEST:
+          if [ "${{ steps.ohi-release-notes.outputs.next-version }}" = "v1.3.0" ] ; then
+            echo PASS
+          else
+            echo FAIL - action output 'next-version' does not return the expected value
+            ((exit_status++))
+          fi
+          echo =================================================================
+          echo "action output 'release-title' return the expected value"
+          echo EXPECTED:
+          echo "v1.3.0 - $(date +%Y-%m-%d)"
+          echo RESULT:
+          echo "${{ steps.ohi-release-notes.outputs.release-title }}"
+          echo TEST:
+          if [ "${{ steps.ohi-release-notes.outputs.release-title }}" = "v1.3.0 - $(date +%Y-%m-%d)" ] ; then
+            echo PASS
+          else
+            echo FAIL - action output 'release-title' does not return the expected value
+            ((exit_status++))
+          fi
+
+          exit $exit_status
